### ISSUE TITLE
Tracking issue of open problems related to Avatar Graphs

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/avatar_graph#49]
This issue is for keeping track of open problems related to Avatar Graphs.

It is not meant to be an exhaustive list of problems which solutions measure progress of understanding these graphs.
A todo-list can be distractive from working on the most important problems, because understanding which problems are important is harder than generating a list of problems. I believe it is likely that the key insights will come from unexplored ideas or questions which have not yet been asked. However, at the current stage, it might be easier to find those new ideas by organizing the existing ones.

### Technical problems

These are problems which ideas are well understood, but might require theorem proving or review of mathematical literature.

- [x] Conjecture: Is every filled Avatar Graph isomorphic to some hypercube? (Counter-proof exists. See https://github.com/advancedresearch/avatar_graph/issues/19)
- [x] Conjecture: Every filled Avatar Graph contains `2^n` nodes (Counter-proof exists. See https://github.com/advancedresearch/avatar_graph/issues/51)
- [ ] How many filled Avatar Graphs are there of `2^n` nodes?
 - Suggestion: Develop algorithms to enumerate these spaces
 - Suggestion: Develop conjecture algorithm to predict the number sequence directly (`s(n)`, index set)
- [ ] Can semi-contractibility be avoided in a symmetrical way?
 - For general discussion about semi-contractibility, see https://github.com/advancedresearch/avatar_graph/issues/37
 - Suggestion: Study permutations of node order over avatar distance contractibility 
 - [ ] Does every filled Avatar Graph have a unique interpretation? (suggested by Daniel Fischer)

### Philosophical problems

These are problems which ideas are not well understood yet.

- [ ] How does combinatorial properties of filled Avatar Graphs work?
 - Suggestion: Study the "trivial" case where orthogonal graphs give rise to Hypercubes
- [ ] How does order independent calculations of avatar distances work?
 - Suggestion: Study calculations of avatar distances, step by step, using different node order
- [ ] Can edge order influence current algorithms? (node vs edge order)
 - Suggestion: Design an experiment to study node vs edge order
- [ ] How are Avatar Graphs understood when embedded in other Avatar Graphs?
 - Suggestion: Study sub-sets of a graph, overlaying information for comparison
- [ ] How are filled Avatar Graphs related to topological spaces?
- [ ] How are Avatar Graphs related to adjoint functors or adjoint paths?
 - For more information about adjont paths, see paper [Adjoint Paths](https://github.com/advancedresearch/path_semantics/blob/master/papers-wip/adjoint-paths.pdf)
- [ ] Do Avatar Graphs model some property of macroscopic physical observers?
 - Suggestion: Investigate physical limitations on organizing information/memory in space-time
- [ ] Can Avatar Graphs give insights on how to tackle the hard problem of consciousness?
 - Suggestion: The idea that consciousness does not reside in a single region of the brain
- [ ] Can Avatar Graphs be interpreted in the context of microscopic physical observers?
 - Suggestion: Particle interactions as ways of forming information processing networks
- [ ] Can some relations in path semantics be modeled using Avatar Graphs, instead of just extending relations?
- [ ] What are interesting path semantical properties of Avatar Graphs?
 - Suggestion: Avatar Graphs might be used to predict properties of Avatar Graphs
- [ ] In what sense are Avatar Graphs interesting graphs?
 - Suggestion: Does it make sense to study collection of graph properties, instead of single properties over all graphs?
- [ ] How can a sub-type of graphs be relevant for deep ideas in mathematics?
 - Suggestion: Encoding more complex semantics in a simpler language
